USE query_training;
INSERT INTO engine_details(cylinders, engine_volume, power_hp) VALUES (6,3.0,310)
INSERT INTO car_details(car_brand, car_brand_model, car_type, production_start, production_finish, engine_id) 
	VALUES ('Volkswagen','Polo IV','Hatchback','2002','2007',1)
INSERT INTO car_details(car_brand, car_brand_model, car_type, production_start, production_finish, engine_id) 
	VALUES ('Audi','A6 Avant','Station wagon','2011','2014',6)
INSERT INTO car_details(car_brand, car_brand_model, car_type, production_start, production_finish, engine_id) 
	VALUES ('BMW','M5','Sedan','2011','2014',4)
INSERT INTO car_details(car_brand, car_brand_model, car_type, production_start, production_finish, engine_id) 
	VALUES ('Toyota','Supra V','Coupe','2019','2025',6)